[package]
name = "synthrs-wasm"
version = "0.1.0"
authors = ["Ng Guoyou <ng.guoyou@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.27"

[dependencies.synthrs]
git = "https://github.com/gyng/synthrs"
rev = "cb33a75b1891e97781faf5ee2c27fcd78ab984a3"

[profile.release]
lto = true
